import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import MagicCursor from "@/components/MagicCursor";
import BackgroundEmblem from "@/components/BackgroundEmblem";
import MagicParticles from "@/components/MagicParticles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-[#020202] text-[#E0E0E0] antialiased"> {/* Fondo base oscuro aquí */}
        
        {/* El cursor va primero */}
        <MagicCursor />

        <BackgroundEmblem />

        <MagicParticles />
        
        <Header />
        
        {/* Main con padding para que el header fijo no tape contenido */}
        <main className="pt-24 min-h-screen relative z-10">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}
